version: '3.8'
services:
  ashuapp1:
    image: ashucisco:webappv1  # image i want to build 
    build:  # location & name of dockerfile 
      context: . 
      dockerfile: Dockerfile
    container_name: ashuwebc11 # after image build the container i want to create
    ports: # port forwarding 
    - 1234:80 
